### ISSUE TITLE
few small issues in backend.php

### ISSUE THREAD

**Issue by Ghostthinker** [Ghostthinker/moodle-mod_ivs#10]
[backend.php ](https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/backend.php )

- missing login
- capability checks
- forces developer debug settings
- some weird use of $_REQUEST params without clear use of sanitisation etc.

Related to [this comment](https://tracker.moodle.org/browse/CONTRIB-8173?focusedCommentId=860557&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-860557)

**Comment by n-multimedia** [comment]
fixed in https://github.com/Ghostthinker/moodle-mod_ivs/pull/11/files
