### ISSUE TITLE
License page Instance Identification

### ISSUE THREAD

**Issue by tomraedle** [Ghostthinker/moodle-mod_ivs#14]
The instance identification shows "0" and the player version list ist empty.
This issue is on Moodle 3.9.11 (Build: 20211108) with PHP Version 7.4.26.
<img width="796" alt="Screen Shot 11-25-21 at 09 03 PM" src="https://user-images.githubusercontent.com/16492786/143496951-8d5313e0-1483-4d51-8a54-15b5f2c8fbae.PNG">

**Comment by Ghostthinker** [comment]
Problem solved in our backend.
(this issue was'n caused by the plugin)
