### ISSUE TITLE
curl_init called directly

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#17]
eg: 
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/classes/license/MoodleLicenseController.php#L241

Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you.

Note - this is not a blocker for approval.

**Comment by Ghostthinker** [comment]
We fixed this in our new release https://github.com/Ghostthinker/moodle-mod_ivs/releases/tag/v1.9.619

Thank you for mentioning this issue
