### ISSUE TITLE
functions hidden at bottom of inline php file

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#18]
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/backend.php#L207

these functions shouldn't be there. - you shouldn't mix inline php code with functions.

**Comment by Ghostthinker** [comment]
refactored in https://github.com/Ghostthinker/moodle-mod_ivs/commit/f0b337d97cb284c9e70d90f28b41de57b9ac8e0e
