### ISSUE TITLE
incorrect location for settings

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#19]
settings should be defined within the ivs or mod_ivs space eg this is correct:
```
$settings->add(new admin_setting_heading('mod_ivs/ivssettings'
```
This one is incorrect
```
$settings->add(new admin_setting_configcheckbox('ivs_panopto_external_files_enabled'
```

**Comment by Ghostthinker** [comment]
fixed in https://github.com/Ghostthinker/moodle-mod_ivs/commit/f0b337d97cb284c9e70d90f28b41de57b9ac8e0e
