### ISSUE TITLE
Fragile use of isteacher, reliance on role archetypes

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#21]
I see a lot references to isteacher type calls that use role-based checks - also what appears to be some reliance on role archetypes instead of correctly implementing the use of Moodle capabilities - this should really be revisited and rewritten to rely on moodle's capabilities correctly.

**Comment by Ghostthinker** [comment]
We fixed this in our new release https://github.com/Ghostthinker/moodle-mod_ivs/releases/tag/v1.9.619

Thank you for mentioning this issue
