### ISSUE TITLE
Please improve plugins db description

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#23]
the plugins db description really needs to "sell" your plugin a lot better - what features does it have, what can users do with it - maybe add a few more screenshots - mention panopto support etc etc.

This one is definitely a blocker for approval

**Comment by Ghostthinker** [comment]
We fixed this in our new release https://github.com/Ghostthinker/moodle-mod_ivs/releases/tag/v1.9.619

Thank you for mentioning this issue
