### ISSUE TITLE
Error installing mod_ivs on Moodle 4.0.3 via cli

### ISSUE THREAD

**Issue by peta3000** [Ghostthinker/moodle-mod_ivs#26]
Dear devs

When installing Moodle with the mod_ivs plugin included using the cli scripts (install.php and install-database.php), the installation is aborted and I get the following error message:

```
Default exception handler: Unsupported redirect detected, script execution terminated Debug: 
Error code: redirecterrordetected
* line 2838 of /lib/weblib.php: moodle_exception thrown
* line 2842 of /lib/moodlelib.php: call to redirect()
* line 31 of /mod/ivs/settings.php: call to require_login()
* line 140 of /lib/classes/plugininfo/mod.php: call to include()
* line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
* line 8927 of /lib/adminlib.php: call to require()
* line 8953 of /lib/adminlib.php: call to admin_get_root()
* line 522 of /lib/installlib.php: call to admin_apply_default_settings()
* line 186 of /admin/cli/install_database.php: call to install_cli_database()

!!! Unsupported redirect detected, script execution terminated !!!
!! 
Error code: redirecterrordetected !!
!! Stack trace: * line 2838 of /lib/weblib.php: moodle_exception thrown
* line 2842 of /lib/moodlelib.php: call to redirect()
* line 31 of /mod/ivs/settings.php: call to require_login()
* line 140 of /lib/classes/plugininfo/mod.php: call to include()
* line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod-&gt;load_settings()
* line 8927 of /lib/adminlib.php: call to require()
* line 8953 of /lib/adminlib.php: call to admin_get_root()
* line 522 of /lib/installlib.php: call to admin_apply_default_settings()
* line 186 of /admin/cli/install_database.php: call to install_cli_database()

```

Best regards

peta

**Comment by stphprom** [comment]
Hi,

could you provide us the exact shell command that you use to install (without credentials) your site. We could not reproduce this behaviour on a fresh install.

**Comment by peta3000** [comment]
Hi @stphprom thanks for your reply!

Please proceed as following to reproduce the issue:

1. set up a vm (I used debian 11)
2. update packages and install git
3. install docker-engine (and other necessary tools like curl):
https://docs.docker.com/engine/install/debian/
4. install docker-compose
https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-debian-10
5. create directory, cd into it and clone a moodle repo:
https://github.com/moodle/moodle
6. (rename it if you want to), cd into moodle-directory it and switch (or checkout) to branch MOODLE_400_STABLE
7. install the mod_ivs plugin as submodule:
`git submodule -b master https://github.com/Ghostthinker/moodle-mod_ivs.git mod/ivs`
8. check whether submodul has been installed:
`cat .gitmodules`
10. `cd ..` again a level deeper
11. clone the moodle-docker repo (form moodlehq):
https://github.com/moodlehq/moodle-docker
12. cd into
13. since docker commands (including docker-compose) on default need sudo rights to be run in Linux login/change into superuser or root:
`sudo su`
14. now within moodle-docker directory run the setup described in its README file:
https://github.com/moodlehq/moodle-docker#quick-start

save some environment variables:
Set up path to Moodle code (--> the absolute path to the moodle directory you just cloned)
`export MOODLE_DOCKER_WWWROOT=/path/to/moodle/code`

Choose a db server (Currently supported: pgsql, mariadb, mysql, mssql, oracle)
--> I used pgsql
`export MOODLE_DOCKER_DB=pgsql`

Ensure customized config.php for the Docker containers is in place
--> copy it as is
cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php

Start up containers
bin/moodle-docker-compose up -d

--> this will built and start up the containers and already run the php script "install.php" also creating an empty database

15. check the running containers:
`docker ps`

lookup and copy the CONTAINER ID of container from image: moodlehq/moodle-php-apache:7.4 and copy it 
(it's the webserver, which should be possible to reach via browser from localhost  https://127.0.0.1:8000)

16. access the container in interactive shell mode by providing the necessary CONTAINER-ID:
`docker excec -it "CONTAINER-ID" /bin/bash
`
17. navigate to the php-scripts:
`cd admin/cli
`
18. since an empty dababase has already been created and is running within own container we need to complete the installation by running the install_database.php script and also provide some options (agreeing to licence, adminuser name and password)
`php install_database.php --agree-license --adminuser=admin --adminpass=adminadmin` 


now the script will start to run in verbose mode running through the installation items.
After "logstore_standard" it should exit with following error message:
```
.
.
.
++ Success ++
-->logstore_legacy
++ Success ++
-->logstore_standard
++ Success ++
Default exception handler: Unsupported redirect detected, script execution terminated Debug: 
Error code: redirecterrordetected
* line 2838 of /lib/weblib.php: moodle_exception thrown
* line 2835 of /lib/moodlelib.php: call to redirect()
* line 31 of /mod/ivs/settings.php: call to require_login()
* line 140 of /lib/classes/plugininfo/mod.php: call to include()
* line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
* line 8927 of /lib/adminlib.php: call to require()
* line 8953 of /lib/adminlib.php: call to admin_get_root()
* line 522 of /lib/installlib.php: call to admin_apply_default_settings()
* line 186 of /admin/cli/install_database.php: call to install_cli_database()

!!! Unsupported redirect detected, script execution terminated !!!
!! 
Error code: redirecterrordetected !!
!! Stack trace: * line 2838 of /lib/weblib.php: moodle_exception thrown
* line 2835 of /lib/moodlelib.php: call to redirect()
* line 31 of /mod/ivs/settings.php: call to require_login()
* line 140 of /lib/classes/plugininfo/mod.php: call to include()
* line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod-&gt;load_settings()
* line 8927 of /lib/adminlib.php: call to require()
* line 8953 of /lib/adminlib.php: call to admin_get_root()
* line 522 of /lib/installlib.php: call to admin_apply_default_settings()
* line 186 of /admin/cli/install_database.php: call to install_cli_database()
 !!
```


Run the installation without the plugin first (skipping stepps 7. and 8.) to check first, whether the installation of vanilla Moodle 4.0 works out fine by it self.

If installation completes without errors, kill the containers again
`bin/moodle-docker-compose down`

perform steps 7. and 8. (ad the plugin mod_ivs to the branch as submodule)

built the updated containers again
`bin/moodle-docker-compose up -d`

and continue from step 15. on

**Comment by Ghostthinker** [comment]
Thank you for the detailed response. We have figured out the problem and will release the fix during the next week. We will reply again when the fix is available.

**Comment by Ghostthinker** [comment]
The fix is now available. You can get it [here ](https://moodle.org/plugins/mod_ivs)or visit our Moodle directory page

**Comment by peta3000** [comment]
Dear @Ghostthinker thanks a lot for the quick patching!
Best regards
p
