### ISSUE TITLE
NOT is not a boolean

### ISSUE THREAD

**Issue by nexterday** [Ghostthinker/moodle-mod_ivs#27]
https://github.com/Ghostthinker/moodle-mod_ivs/blob/8707dbda9806df871c5e23dad333b819369cdfff/db/upgrade.php#L105 and line L106

What is NOT? Regardless, it need to be used as CHAR  - with single quote (as per install.xml table ivs_settings definition).

**Comment by Ghostthinker** [comment]
"NOT" inverts here the value for the specific settings. Do you use a MySQL or a Postgres as database?

**Comment by nexterday** [comment]
Postgres.

Either use:
`NOT(COALESCE(value, FALSE))` instead of NOT value
Or
Add `RETURNING *` at the end of sentence. <— not sure if this would work in mysql. 

Ps moodle db api supports many database engines, hence safety factor is more important than fancy shortcuts. Ie even if you retrieve the values, then invert them, then update the records, its still accepted as the script is called once off and most probably never again.

**Comment by nexterday** [comment]
for postgres, please use:  `value = NOT cast(value as boolean)` or `value = NOT value::boolean`
for mysql, your statement might work out of luck, but for an inclusive and safe solution: moodle db api supports many database engines, hence safety factor is more important than fancy shortcuts. Ie even if you retrieve the values, then invert them, then update the records, its still accepted as the script is called once off and most probably never again.

P.S needs to be changed in/for line 105 and 106.

**Comment by Ghostthinker** [comment]
Thank you, for your feedback. You are correct, that seems a little bit hacky todo the shortcut. We will commit an update where we use the moodle database api and transactions for flipping the values.

**Comment by Ghostthinker** [comment]
We have created a new release. The upgrade should now be feasible. Thank you for the detailed informations
