### ISSUE TITLE
Exception - Class "mod_ivs\UpdateService" not found

### ISSUE THREAD

**Issue by voltere5** [Ghostthinker/moodle-mod_ivs#28]
![image](https://user-images.githubusercontent.com/37559303/191440800-59b49472-cf9c-45cf-8093-3db97e3fe384.png)

$plugin->component = 'mod_ivs';
$plugin->release = 'v1.13.809';
$plugin->version = 2022092000;
$plugin->requires = 2014051200;
$plugin->maturity = MATURITY_BETA;
$plugin->cron = 0;
$plugin->dependencies = array();

**Comment by Ghostthinker** [comment]
Hallo and thank you for pointing out this issue. We provided a new release which fix the issue.
