### ISSUE TITLE
MoodleLicenseController.php displays error messages on licence page

### ISSUE THREAD

**Issue by sennewood** [Ghostthinker/moodle-mod_ivs#29]
- **Moodle**: 3.9.19
- **IVS**: 2022110200
- **Page**: <moodle-url>/mod/ivs/admin/admin_settings_license.php

After I clicked on "Licence" in the Admin UI, I got messages of the same two lines of code over and over:

```log
Notice: Trying to get property 'instance_id' of non-object in /var/www/moodle_3.9.19/mod/ivs/classes/license/MoodleLicenseController.php on line 72

Notice: Trying to get property 'instance_id' of non-object in /var/www/moodle_3.9.19/mod/ivs/classes/license/MoodleLicenseController.php on line 74
```

**Comment by Ghostthinker** [comment]
this notice could occur if you migrated to another server or reinstalled the plugin. 
could you please try to reset your instance_id by calling the following snippet. 

`unset_config('ivs_instance_id', 'mod_ivs');`

**Comment by sennewood** [comment]
From within the Moodle `config.php` or from the `admin_settings_license.php`?

**Comment by Ghostthinker** [comment]
You can unset it in the admin_settings_license.php in line 53. Then visit the page /mod/ivs/admin/admin_settings_license.php and it will be unsetted. Please remove that line after you visted the page!

For more details you could also print the response from the instance call by adding a print method like die(); 

This can be added in the mod/ivs/classes/license/MoodleLicenseController.php in line 72



```php
        if ($response = $this->core_register($instanceid)) {
            die($response);
            $responseobj = json_decode($response);
            set_config('ivs_instance_id', $responseobj->instance_id, 'mod_ivs');
            set_config('ivs_schedule_task', date('Y-m-d H:i:s', time()), 'mod_ivs');
            return $responseobj->instance_id;
        }
        die('No response');
        return false;
```

**Comment by sennewood** [comment]
Thank you.
