### ISSUE TITLE
incorrect license used in Moodle code.

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#3]
Please see the comments in CONTRIB-8173 for more info on this - please comment there when you have resolved this.

**Comment by n-multimedia** [comment]
thank you. we changed the license https://github.com/Ghostthinker/moodle-mod_ivs/commit/ba1b0c33c16b8c36b03b279eff1e0684e09d48dc

**Comment by tmuras** [comment]
Thanks for updating it, I think you missed the entry in just 2 places:
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/mod_form.php#L39
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/backup/moodle2/backup_course_ivs_settings_step.class.php#L32

**Comment by n-multimedia** [comment]
thank you! we've corrected the license
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/mod_form.php#L39
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/backup/moodle2/backup_course_ivs_settings_step.class.php#L32
