### ISSUE TITLE
sql functions must use placeholders

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#4]
In your sql queries you must use placeholders instead of including vars in-line within the sql - more information here:
https://docs.moodle.org/dev/Data_manipulation_API#Placeholders

**Comment by n-multimedia** [comment]
added sql query placeholders
https://github.com/Ghostthinker/moodle-mod_ivs/blob/fc338fc3ea98b31bbb9f8b0c0f6dfe6f95435c90/classes/AnnotationService.php#L156
