### ISSUE TITLE
hard-coded role names/ids

### ISSUE THREAD

**Issue by danmarsden** [Ghostthinker/moodle-mod_ivs#8]
https://github.com/Ghostthinker/moodle-mod_ivs/blob/9ae11a459d459a6a51e30aa457bd1c21537e04cf/view.php#L74-L100

Many organisations will customise their roles and you cannot guaruntee the id numbers you are using there will actually match with the correct student/teacher roles - this is not the right way to determine user access - please use capabilities rather than roles.

The best method is to create new capabilities in your plugin that are assigned to the relevant roles by default, and then check if the current user has that capability in this context.

FYI - This is a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
btw - if you really need to check for site admin - the api function is_siteadmin() is the better way to go rather than getting it from get_admins().

**Comment by n-multimedia** [comment]
good point, thank you. we've just fixed this issue:
https://github.com/Ghostthinker/moodle-mod_ivs/blob/master/view.php
